name = "vhlink"
type = "javascript"
account_id = "670ade1150d4d3dc4b3eb2e9d48ea7ca"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "a690469fc0ec43638658f1bf372941aa", preview_id = "a690469fc0ec43638658f1bf372941aa" }
]
